version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestGitFeatureStageProject
  gitServerName: SanthoshK
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
services:
- serviceName: project.testgitfeaturestage.integrations:TestGitFeature
  packages:
  - name: TestGitFeatureStageProject
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.1962
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.1962
